In [3]:
from offpolicy.algorithms.qmix.qmix import QMix

In [50]:
import torch
from torch.distributions import Categorical

l = torch.ones(6, 3)
print(l)
r = Categorical(logits=l).sample()
print(r)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([1, 0, 2, 1, 1, 1])


In [31]:
import numpy as np

b = np.zeros((10, 3, 1))
b

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [32]:
a = np.ones((10, 1, 1))
a

array([[[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]]])

In [ ]:
a[0,]

In [ ]:
b[:,0:1,:] = a
b

In [69]:
torch.vstack((r,r))

tensor([[1, 0, 2, 1, 1, 1],
        [1, 0, 2, 1, 1, 1]])

In [16]:
a = [np.zeros(5)] * 2
a

[array([0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0.])]

In [17]:
np.stack(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
a = [np.arange(5)] * 2
a

[array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])]

In [30]:
np.tile(np.concatenate(a), (2,1))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

In [34]:
np.vstack([1, 2])

array([[1],
       [2]])

In [2]:
import torch
a = torch.zeros((10, 23, 43))
a[0].shape

torch.Size([23, 43])

In [39]:
torch.cat([torch.zeros(1,5), torch.zeros(1, 5)])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [9]:
import numpy as np
a = [np.zeros((1,5)), np.zeros((1, 5))]
torch.Tensor(np.concatenate(a, axis=1))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [2]:
m = 200

for i in range(50):
    if m<1000:
        m += m * 0.12
    elif m<5000:
        m += m * 0.06
    
    print(i + 1, m)
    

1 224.0
2 250.88
3 280.9856
4 314.703872
5 352.46833663999996
6 394.76453703679994
7 442.1362814812159
8 495.19263525896184
9 554.6157514900373
10 621.1696416688417
11 695.7099986691027
12 779.195198509395
13 872.6986223305224
14 977.4224570101851
15 1094.7131518514072
16 1160.3959409624917
17 1230.0196974202413
18 1303.8208792654557
19 1382.050132021383
20 1464.973139942666
21 1552.871528339226
22 1646.0438200395795
23 1744.8064492419542
24 1849.4948361964714
25 1960.4645263682596
26 2078.092397950355
27 2202.7779418273763
28 2334.9446183370187
29 2475.04129543724
30 2623.5437731634743
31 2780.9563995532826
32 2947.8137835264797
33 3124.6826105380683
34 3312.1635671703525
35 3510.8933812005735
36 3721.5469840726078
37 3944.839803116964
38 4181.530191303982
39 4432.422002782221
40 4698.367322949154
41 4980.269362326104
42 5279.08552406567
43 5279.08552406567
44 5279.08552406567
45 5279.08552406567
46 5279.08552406567
47 5279.08552406567
48 5279.08552406567
49 5279.08552406567
50 5279.0