In [3]:
from offpolicy.algorithms.qmix.qmix import QMix

In [50]:
import torch
from torch.distributions import Categorical

l = torch.ones(6, 3)
print(l)
r = Categorical(logits=l).sample()
print(r)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([1, 0, 2, 1, 1, 1])


In [60]:
a = torch.rand(6)
t = (a < 0.5).int()
t

tensor([1, 1, 0, 1, 0, 1], dtype=torch.int32)

In [63]:
(1 - t) * r

tensor([0, 0, 2, 0, 1, 0])

In [70]:
torch.eye(3)[torch.vstack((r,r))]

tensor([[[0., 1., 0.],
         [1., 0., 0.],
         [0., 0., 1.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]],

        [[0., 1., 0.],
         [1., 0., 0.],
         [0., 0., 1.],
         [0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]]])

In [69]:
torch.vstack((r,r))

tensor([[1, 0, 2, 1, 1, 1],
        [1, 0, 2, 1, 1, 1]])