In [3]:
from offpolicy.algorithms.qmix.qmix import QMix

In [50]:
import torch
from torch.distributions import Categorical

l = torch.ones(6, 3)
print(l)
r = Categorical(logits=l).sample()
print(r)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([1, 0, 2, 1, 1, 1])


In [31]:
import numpy as np

b = np.zeros((10, 3, 1))
b

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [32]:
a = np.ones((10, 1, 1))
a

array([[[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]],

       [[1.]]])

In [ ]:
a[0,]

In [ ]:
b[:,0:1,:] = a
b

In [69]:
torch.vstack((r,r))

tensor([[1, 0, 2, 1, 1, 1],
        [1, 0, 2, 1, 1, 1]])

In [16]:
a = [np.zeros(5)] * 2
a

[array([0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0.])]

In [17]:
np.stack(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
a = [np.arange(5)] * 2
a

[array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])]

In [30]:
np.tile(np.concatenate(a), (2,1))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

In [34]:
np.vstack([1, 2])

array([[1],
       [2]])

In [38]:
import torch
a = torch.zeros((10, 23, 43))
a[0].shape

torch.Size([23, 43])