In [3]:
from offpolicy.algorithms.qmix.qmix import QMix

In [50]:
import torch
from torch.distributions import Categorical

l = torch.ones(6, 3)
print(l)
r = Categorical(logits=l).sample()
print(r)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([1, 0, 2, 1, 1, 1])


In [9]:
import numpy as np

b = np.zeros((10, 3, 5))
b

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [14]:
a = np.ones((10, 1, 5))
a

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [15]:
b[:,0:1,:] = a
b

array([[[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [69]:
torch.vstack((r,r))

tensor([[1, 0, 2, 1, 1, 1],
        [1, 0, 2, 1, 1, 1]])

In [16]:
a = [np.zeros(5)] * 2
a

[array([0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0.])]

In [17]:
np.stack(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])